
// This file has been generated by the GUI designer. Do not modify.
namespace TunrSync
{
	public partial class LogInWindow
	{
		private global::Gtk.Alignment alignment1;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Image ImageLogo;
		
		private global::Gtk.Label LabelEmail;
		
		private global::Gtk.Entry EntryEmail;
		
		private global::Gtk.Label LabelPassword;
		
		private global::Gtk.Entry EntryPassword;
		
		private global::Gtk.Alignment alignment2;
		
		private global::Gtk.Button BtnLogIn;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TunrSync.LogInWindow
			this.WidthRequest = 320;
			this.HeightRequest = 320;
			this.Name = "TunrSync.LogInWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 320;
			this.DefaultHeight = 320;
			// Container child TunrSync.LogInWindow.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(48));
			this.alignment1.RightPadding = ((uint)(48));
			this.alignment1.BottomPadding = ((uint)(16));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.ImageLogo = new global::Gtk.Image ();
			this.ImageLogo.Name = "ImageLogo";
			this.ImageLogo.Ypad = 24;
			this.ImageLogo.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "Assets\\TunrText.png"));
			this.vbox1.Add (this.ImageLogo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.ImageLogo]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.LabelEmail = new global::Gtk.Label ();
			this.LabelEmail.Name = "LabelEmail";
			this.LabelEmail.Xalign = 0F;
			this.LabelEmail.LabelProp = global::Mono.Unix.Catalog.GetString ("E-mail");
			this.vbox1.Add (this.LabelEmail);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.LabelEmail]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.EntryEmail = new global::Gtk.Entry ();
			this.EntryEmail.CanFocus = true;
			this.EntryEmail.Name = "EntryEmail";
			this.EntryEmail.IsEditable = true;
			this.EntryEmail.InvisibleChar = '●';
			this.vbox1.Add (this.EntryEmail);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.EntryEmail]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.LabelPassword = new global::Gtk.Label ();
			this.LabelPassword.Name = "LabelPassword";
			this.LabelPassword.Xalign = 0F;
			this.LabelPassword.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
			this.vbox1.Add (this.LabelPassword);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.LabelPassword]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.EntryPassword = new global::Gtk.Entry ();
			this.EntryPassword.CanFocus = true;
			this.EntryPassword.Name = "EntryPassword";
			this.EntryPassword.IsEditable = true;
			this.EntryPassword.Visibility = false;
			this.EntryPassword.InvisibleChar = '●';
			this.vbox1.Add (this.EntryPassword);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.EntryPassword]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.LeftPadding = ((uint)(32));
			this.alignment2.RightPadding = ((uint)(32));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.BtnLogIn = new global::Gtk.Button ();
			this.BtnLogIn.HeightRequest = 32;
			this.BtnLogIn.CanFocus = true;
			this.BtnLogIn.Name = "BtnLogIn";
			this.BtnLogIn.UseUnderline = true;
			this.BtnLogIn.Label = global::Mono.Unix.Catalog.GetString ("Log In");
			this.alignment2.Add (this.BtnLogIn);
			this.vbox1.Add (this.alignment2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment2]));
			w7.PackType = ((global::Gtk.PackType)(1));
			w7.Position = 6;
			w7.Expand = false;
			w7.Fill = false;
			this.alignment1.Add (this.vbox1);
			this.Add (this.alignment1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.EntryEmail.Activated += new global::System.EventHandler (this.BtnLogIn_clicked);
			this.EntryPassword.Activated += new global::System.EventHandler (this.BtnLogIn_clicked);
			this.BtnLogIn.Clicked += new global::System.EventHandler (this.BtnLogIn_clicked);
		}
	}
}
